### ISSUE TITLE
Google drive permission for pre-trained weights

### ISSUE THREAD

**Issue by Roziallegro** [AaronComo/LipFD#10]
Hello, may I know when will the [pre-trained weights ](https://drive.google.com/file/d/1NPAcx0QS8N9v_9qUr-51jBaL9kGDT-cp/view?usp=share_link) be publicly available?

Or is there a verification required by sending a proper email?

**Comment by twilight2001** [comment]
Hi we're non-profit research doing some eval for government, also very interested in testing the pre-train weights, see email please !
